# Generated by Django 5.0 on 2023-12-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorName', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=35)),
                ('phone', models.CharField(max_length=12)),
                ('catName', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=22)),
                ('size', models.CharField(max_length=15)),
                ('breed', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('adoptionStatus', models.BooleanField(default=False)),
                ('personality', models.TextField(blank=True)),
            ],
        ),
    ]
