# Generated by Django 5.0 on 2023-12-12 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cats',
            name='donorName',
        ),
        migrations.RemoveField(
            model_name='cats',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cats',
            name='phone',
        ),
    ]
